disabled_rules:
    - trailing_whitespace
    - vertical_whitespace

included:
    - V2EX-Swift

excluded:
    - Pods
    - V2EX-Swift/R.generated.swift
    - V2EX-Swift/Vendor

type_name:
    min_length:
        warning: 2
        error: 1
    excluded:
        - T
        - E

identifier_name:
    min_length:
        warning: 2
        error: 1
    excluded:
        - i
        - x
        - y
        - id
